### PR TITLE
Fix garbled Chinese response in browser. close #1559

### LINKED ISSUE #1559: The custom plug-in returns the result garbled
### code:
```
function _M.access(conf, ctx)
    ...
    log.warn(">>>>>>>>>>>>>>>>>>", data)
    local accept_type = ngx.req.get_headers()["Accept"]
    if str_contains(accept_type, "text/html") then
        return 200, data
    else
        return 200, decode(data)
    end
end
```
> The data comes from the cache

### log:
```
2020/05/09 10:55:59 [warn] 23640#0: *812 [lua] dfy-cache-plugin.lua:380: phase_fun(): >>>>>>>>>>>>>>>>>>{"data":"测试服务器8001"}
, client: 172.30.212.72, server: , request: "GET /read?_YCD_={%22read%22:%20[%2211111111111%22]} HTTP/1.1", host: "172.30.212.72:9080"
```

### result:
```
{"data":"æµ‹è¯•æœåŠ¡å™¨8001"}
```

I think the reason is that the encoding is not configured in nginx.conf. Can we add utf-8 encoding into it or specify the encoding through configuration?

### PR DESCRIPTION
**Pull request by xxm404**
https://github.com/apache/incubator-apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one

### Summary

Modify APISIX Nginx template to solve #1559

### Full changelog

* Add `charset utf-8;` in APISIX Nginx config template

### Issues resolved

Fix #1559

### CODE REVIEW

**Comment by moonming** [comment]
@xxm404 it will be better if you can add test cases for this PR

**Comment by xxm404** [comment]
> @xxm404 it will be better if you can add test cases for this PR

This problem only occurred in the browser, how to test by test Nginx

**Comment by griffenliu** [comment]
Hi, @xxm404 :
Consider the following code for increased  flexibility?
```
include mime.types;
{% if http.charset then %}
charset {* http.charset *};
{% end %}
```

**Comment by xxm404** [comment]
> Hi, @xxm404 :
> Consider the following code for increased flexibility?
> 
> ```
> include mime.types;
> {% if http.charset then %}
> charset {* http.charset *};
> {% end %}
> ```

Good idea, But in my opinion, Nginx charset won't be modified frequently, We shouldn't complicate config.yaml

**Comment by membphis** [comment]
@xxm404 many thx, merged already

**Pull request merged**
