### PR TITLE
Adding tcp logger.

### LINKED ISSUE #1220: Add TCP logger plugin.
### Issue description

I found udp logger plugin already in the project as a plugin. I would like to add TCP logger which provides more secure logging capabilities.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
### Summary

Adding support to tcp logger plugin.

### Full changelog

Started working on tcp logger plugin

Referring these 2 repos :- https://github.com/openresty/lua-nginx-module#udpsocksetpeername
https://github.com/fluent/fluent-logger-node

I am more familiar with node.js so I thought it would help me. to understand the flow

### Issues resolved

Fix #1220

### CODE REVIEW

**Comment by Akayeshmantha** [comment]
Hi @membphis  @moonming  

I completed the tcp logger but am getting below error in a unit test (test 5 access). 

`Failed test 'TEST 5: access - pattern "[error]" should not match any line in error.log but matches line "2020/03/11 09:41:17 [error] 26326\#26326: *21 [lua] tcp-logger.lua:61: failed to connect to TCP server: host[127.0.0.1] port[2001] connection refused, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:1984" (req 0)`

Any thoughts am actually blocked here

**Comment by moonming** [comment]
@Akayeshmantha  the test case 5 will connect tcp log server `127.0.0.1:5044`, which not exist, so it will fail.
you can mock tcp log server like this: https://github.com/apache/incubator-apisix/blob/master/t/APISIX.pm#L107

**Comment by Akayeshmantha** [comment]
Finally thanks @moonming

**Comment by moonming** [comment]
need add plugin doc and README.md.

**Comment by Akayeshmantha** [comment]
@moonming  added thanks.

**Comment by Akayeshmantha** [comment]
@moonming added the readme file and the document.

**Comment by Akayeshmantha** [comment]
@membphis  @moonming  can we merge this PR. If the read me doc is ok I can add udp plugin readme as well.

**Comment by membphis** [comment]
merged, many thx

**Pull request merged**
