### PR TITLE
add profile to core lua configs.

### LINKED ISSUE #1184: bug: failed to call `apisix init` after apisix was installed by luarocks
### Issue description

https://travis-ci.org/apache/incubator-apisix/jobs/657178537#L1420

### Environment

* apisix version (cmd: `apisix version`):  https://github.com/apache/incubator-apisix/commit/e1ac426443293c6140ddb257e482537edd43c36a
* OS: ubuntu

### Minimal test code / Steps to reproduce the issue
https://github.com/apache/incubator-apisix/blob/master/.travis/linux_apisix_luarocks_runner.sh

### PR DESCRIPTION
**Pull request by Akayeshmantha**
### Full changelog
Add profile in the core module.

### Issues resolved

Fix #1184

### CODE REVIEW

**Comment by membphis** [comment]
Looks good, I will test it manually as soon as possible

**Comment by membphis** [comment]
merged,many thx @Akayeshmantha

**Comment by moonming** [comment]
@membphis CI failed, why merged? https://travis-ci.org/apache/incubator-apisix/jobs/659177144#L1431

**Comment by membphis** [comment]
The old CI run e2e test with master branch.

Tt has been fixed  by this PR: https://github.com/apache/incubator-apisix/commit/b835bb79f1bffe0c7db734c492eabea793e1d5da

**Pull request merged**
