### PR TITLE
Improve how to test instructions

### PR DESCRIPTION
**Pull request by sshniro**
Added additional info to run in OSx platform and to run individual test cases

### CODE REVIEW

**Comment by sshniro** [comment]
hello, @membphis how can I fix this mac os issue? or does this fail by default

**Comment by membphis** [comment]
it is unstable, we can re-run it

image

**Comment by membphis** [comment]
@sshniro We should do the development in our own repository, avoid to create branch at APISIX repository.

image

**Comment by sshniro** [comment]
> @sshniro We should do the development in our own repository, avoid to create branch at APISIX repository.
> 
> image

Aw! Now only noticed, the edit button in Github creates the branch in the main repo itself, I will close this PR and create a new one.
image

**Comment by sshniro** [comment]
@membphis there is also another branch with my name in the APISIX repo, shall I also delete it?

image

**Comment by membphis** [comment]
yes, we need to remove this branch. it is useless for other people.

**Pull request closed without merging**
