### PR TITLE
add skywalking plugin instructions

### PR DESCRIPTION
**Pull request by cyxinda**
NOTE: Please read the Contributing.md guidelines before submitting your patch:

https://github.com/apache/incubator-apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one

### Summary

SUMMARY_HERE

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issues resolved

Fix #XXX

### CODE REVIEW

**Comment by membphis** [comment]
please take a look at the outputs of Travis-CI:

https://travis-ci.org/github/apache/incubator-apisix/jobs/693361232
```
Reading configuration file [.travis/ASF-Release.cfg]...
Scanning files starting at [./]...
Scan detected 95 error(s) in 2 file(s):
  [./doc/plugins/skywalking-cn.md]:
      85: line contains tabs.
      86: line contains tabs.
      87: line contains tabs.
      88: line contains tabs.
      90: line contains tabs.
      91: line contains tabs.
      92: line contains tabs.
      93: line contains tabs.
      95: line contains tabs.
      96: line contains tabs.
      97: line contains tabs.
      98: line contains tabs.
      98: line has trailing whitespace.
      99: line contains tabs.
     100: line contains tabs.
```

**Comment by cyxinda** [comment]
I have removed the tabs character.

**Comment by moonming** [comment]
```
Scan detected 15 error(s) in 2 file(s):

  [./doc/plugins/skywalking-cn.md]:

      98: line has trailing whitespace.

     102: line has trailing whitespace.

     116: line has trailing whitespace.

     122: line has trailing whitespace.

     127: line has trailing whitespace.

     128: line has trailing whitespace.

     129: line has trailing whitespace.

  [./doc/plugins/skywalking.md]:

      37: line has trailing whitespace.

      85: line has trailing whitespace.

     100: line has trailing whitespace.

     104: line has trailing whitespace.

     118: line has trailing whitespace.

     124: line has trailing whitespace.

     130: line has trailing whitespace.

     131: line has trailing whitespace.
```
@cyxinda please take a look

**Comment by cyxinda** [comment]
have done.

发自我的iPhone

**Comment by moonming** [comment]
@cyxinda merged, thx

**Comment by cyxinda** [comment]
发自我的iPhone

**Pull request merged**
