### PR TITLE
separate prometheus and access log

### PR DESCRIPTION
**Pull request by DHB-liuhong**
Signed-off-by: liuhong <dhbliuhong@163.com>

### Summary

separate prometheus and access log

### CODE REVIEW

**Comment by membphis** [comment]
Why do we need this feature?

**Comment by DHB-liuhong** [comment]
I think it is need to separate prometheus and access log，it is good for analysing log.

**Comment by membphis** [comment]
I do not think so. the `uri` is very different, it is easy to confirm if it is `prometheus` request.

**Comment by DHB-liuhong** [comment]
ok

**Pull request closed without merging**
