### PR TITLE
doc: add FAQ about redirect http To https

### PR DESCRIPTION
**Pull request by rhubard**

### CODE REVIEW

**Comment by agile6v** [comment]
Can this feature be supported in rewrite plugin?

**Comment by rhubard** [comment]
> Can this feature be supported in rewrite plugin?

```shell
[
  {
    "uri": "/*",
    "host": "iresty.com",
    "vars": [
      [
        "scheme",
        "==",
        "http"
      ]
    ],
    "plugins": {
      "redirect": {
        "ret_code": 301,
        "uri": "https://$host$request_uri"
      }
    }
  },
  {
    "uri": "/*",
    "host": "iresty.com",
    "priority": 1,
    "vars": [
      [
        "scheme",
        "==",
        "https"
      ]
    ],
    "upstream": {
      "nodes": {
        "xxxxx": 1
      },
      "type": "roundrobin"
    }
  }
]
```

**Comment by moonming** [comment]
I think you can also add doc and test case for `redirect` plugin.

**Comment by membphis** [comment]
@rhubard can you repush again? The CI is stopped.

**Comment by membphis** [comment]
image

image

@rhubard It seems like a bug of Travis or Github, you can take a look at this PR: https://github.com/apache/incubator-apisix/pull/1397

the commit log is different.

**Comment by moonming** [comment]
> I think you can also add doc and test case for `redirect` plugin.

@rhubard ping

**Comment by membphis** [comment]
@rhubard you can close this PR and submit a new PR.

you

image

**Pull request closed without merging**
