### PR TITLE
feature: support new field `exptime` for SSL object.

### LINKED ISSUE #1571: feature: support new field `exptime` for SSL object
https://github.com/apache/incubator-apisix/blob/master/apisix/schema_def.lua#L447

We need a new field "exptime" to store the expiration time of the SSL certificate.

### PR DESCRIPTION
**Pull request by membphis**
fix #1571.

### CODE REVIEW

**Comment by moonming** [comment]
Aren't these two data `exptime` and `sins` in the public key? Why store them separately?

**Comment by membphis** [comment]
> Aren't these two data `exptime` and `sins` in the public key? Why store them separately?

https://github.com/apache/incubator-apisix/issues/1571#issuecomment-627156849

Not only administrators need to look at it, but background services also need these two values.

Apache APISIX finds and loads certificates based on SNI.

**Comment by moonming** [comment]
This PR can be a temporary implementation that will be refactored later.

**Comment by membphis** [comment]
please click `approve` if it is fine now

**Pull request merged**
