### PR TITLE
[WIP]feature: CORS plugin.

### PR DESCRIPTION
**Pull request by Miss-you**
相关文档：
CORS理解文档
跨域资源共享CORS的那些事（一）
https://blog.csdn.net/qq_15437667/article/details/100695306
跨域资源共享CORS的那些事（二）
https://blog.csdn.net/qq_15437667/article/details/100695467
cors设计文档：
整体迁移自kong，文档正在写

### CODE REVIEW

**Comment by moonming** [comment]
any update? @Miss-you

**Comment by moonming** [comment]
I think it a zombie PR, I will close it 2 days later.

**Comment by moonming** [comment]
consider closed, you can create a new PR if update later.

**Comment by Miss-you** [comment]
I'm sorry for that I had no time to finish this cors plugin.
I will create a new PR for CORS next week.

thanks
yousa

WenMing <notifications@github.com> 于2019年11月6日周三 下午2:54写道：

**Pull request closed without merging**
