### PR TITLE
doc: add coc file

### LINKED ISSUE #1529: request help: Adding code of conduct file
### Issue description
We don't have a CoC file yet, could anyone can help to create one?

### Environment
None

### Reference links:
- [CoC of Apache](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ShiningRush**
resolve #1529

### CODE REVIEW

**Comment by ShiningRush** [comment]
@moonming @membphis Please review it.

**Comment by membphis** [comment]
@ShiningRush we need this line.

https://github.com/apache/skywalking/blob/master/CODE_OF_CONDUCT.md

image

**Comment by ShiningRush** [comment]
@membphis the error of travis is not related with this commit, please check it.

**Comment by membphis** [comment]
merged already thx @ShiningRush

**Pull request merged**
