### PR TITLE
CI: removed travis CI.

### PR DESCRIPTION
**Pull request by moonming**

### CODE REVIEW

**Comment by membphis** [comment]
We can merge this PR after 3-5 days. We need to confirm that GitHub action CI is running steadily.

**Comment by moonming** [comment]
> We can merge this PR after 3-5 days. We need to confirm that GitHub action CI is running steadily.

I do not think so. This PR's travis CI was run 9 hours and still waiting, which is so disappointing

**Comment by membphis** [comment]
we need to fix this at first: https://github.com/apache/incubator-apisix/issues/1837

**Comment by moonming** [comment]
> we need to fix this at first: #1837

The last few PRs have been stable. I would suggest merging first.

**Comment by membphis** [comment]
> The last few PRs have been stable. I would suggest merging first.

I re-run the master branch CI job twice already. Because the status is failed.

**Comment by membphis** [comment]
For non-master branches (such as PR), I also re-run CI two or three times, same reason. 
I think we need to fix #1837 or waiting more time for confirming.

**Comment by membphis** [comment]
Github action run non-OSX test case.
Travis-CI runs the OSX test case(allow failure).

how about this way?

**Comment by moonming** [comment]
LGTM

YuanSheng Wang <notifications@github.com> 于 2020年7月17日周五 下午12:29写道：

**Comment by membphis** [comment]
close this PR, I created a new: https://github.com/apache/incubator-apisix/pull/1860

**Pull request closed without merging**
