### PR TITLE
chore: improve plugins/proxy-cache

### PR DESCRIPTION
**Pull request by spacewander**
1. unit all the default cache time to 10s.
2. remove repeated `if proxy_cache` check.
3. improve `generate_complex_value`'s performance.
4. better indent.

### CODE REVIEW

**Comment by spacewander** [comment]
BTW, the doc mentions that the `502` and `504` returned by APISIX will be cached. However, the `cache_http_status` is configurable and doesn't contain 5xx code by default. IMHO, if you don't configure to cache 5xx code, you don't need to be afraid of it.

**Comment by membphis** [comment]
nice catch! many thx

**Comment by spacewander** [comment]
@membphis 
Just realize one more thing: we might need to blacklist `ngx.var.request_method` (or document them) in the `ngx.var.upstream_cache_key` to make the purge mechanism work. If the cache key contains the request_method which is always `PURGE` during purging, it won't work anymore.

**Comment by membphis** [comment]
you are right, I prefer the blacklist of `ngx.var.request_method`.

**Comment by agile6v** [comment]
> BTW, the doc mentions that the `502` and `504` returned by APISIX will be cached. However, the `cache_http_status` is configurable and doesn't contain 5xx code by default. IMHO, if you don't configure to cache 5xx code, you don't need to be afraid of it.

Hi @spacewander The logic of this plugin is implemented by relying on proxy_no_cache directive. But when the upstream is not available, the APISIX return 502 to client and without running proxy_no_cache directive. 

Do you have any suggestions?

Thanks.

**Comment by spacewander** [comment]
@agile6v 
I see. I figure out that `proxy_no_cache` is skipped when the upstream finalized with 502 or 504. It seems that there is not good pure Lua solution to this problem...

**Pull request merged**
