### PR TITLE
Buffer sys log requests.

### LINKED ISSUE #1500: request help: Alter sys logger to use local batch processor.
### Issue description
Currently, we have sys logger without the support of the batch processor. 
I see there is an issue related to the batch processor because it's not flushing data if the size of the queue did not exceeds.

Will be altering the code of sys logger when that issue is fixed

@membphis  @moonming

### PR DESCRIPTION
**Pull request by Akayeshmantha**
### Summary
Add buffer support sys log.

### Issues resolved

Fix #1500

### CODE REVIEW

**Comment by Akayeshmantha** [comment]
@membphis  @moonming  PR is ready to review.

**Comment by membphis** [comment]
please use `make lint` to check the code style of your code:

```
+luacheck -q apisix
Checking apisix/plugins/syslog.lua                4 warnings
    apisix/plugins/syslog.lua:21:7: unused variable pairs
    apisix/plugins/syslog.lua:22:7: unused variable type
    apisix/plugins/syslog.lua:23:7: unused variable table
    apisix/plugins/syslog.lua:102:49: accessing undefined variable entry
```

**Comment by Akayeshmantha** [comment]
@membphis  done.

**Comment by membphis** [comment]
@Akayeshmantha we need to remove stale objects from `syslog`. we can use a new PR to do this.

I have created a related issue: https://github.com/apache/incubator-apisix/issues/1554

**Pull request merged**
