### PR TITLE
allow failure when exec CI process in MacOS

### PR DESCRIPTION
**Pull request by Zheaoli**

### CODE REVIEW

**Comment by moonming** [comment]
I think better we can finger it out why macOS CI failed.

**Comment by Zheaoli** [comment]
@moonming Yeap，It's just a patch for the code in the master branch.

**Comment by membphis** [comment]
```yaml
services:
  - redis-server
```

Mac does not support this way to start redis server.

**Comment by Zheaoli** [comment]
@membphis here's a problem. Is the Redis a necessary dependency for the test process or it's just optional?

**Comment by membphis** [comment]
Some plugin needs redis server now. 

https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/limit-count.lua#L22

**Comment by Zheaoli** [comment]
maybe we can split the plugin out from the main codebase?

**Comment by membphis** [comment]
> maybe we can split the plugin out from the main codebase?

We don't plan to put the plugin in a separate repository, which makes downloading and installing APISIX difficult.

**Comment by Zheaoli** [comment]
@membphis All right, I will find out a new way to make a full test in MacOS

**Comment by membphis** [comment]
Many thanks

**Pull request merged**
