### PR TITLE
license: remove copyright file.

### PR DESCRIPTION
**Pull request by moonming**

### CODE REVIEW

**Comment by zhiyong0804** [comment]
why remove this file?

**Comment by moonming** [comment]
@zhiyong0804 discussed in mail list: https://lists.apache.org/thread.html/a379504a0aff0311b2cb0bda468b61a043b33cd99abb0632e1c697e7@%3Cdev.apisix.apache.org%3E

**Comment by zhiyong0804** [comment]
approve this pull request

**Comment by moonming** [comment]
> approve this pull request

you are not click approve button yet.

**Pull request merged**
