### PR TITLE
bugfix: drop custom Lua search paths and use Lua standard search path…

### PR DESCRIPTION
**Pull request by membphis**
…s instead.

The different Lua version have different Lua search path.
For example:
  Lua 5.1: /usr/local/share/5.1 or /usr/share/5.1 .
  Lua 5.2: /usr/local/share/5.2 or others.
  Lua 5.3: /usr/local/share/5.3 or others.

### CODE REVIEW

**Comment by membphis** [comment]
dev mail: https://lists.apache.org/thread.html/r2cfef17709f51f2c4dd134ba7274c3bad3242917ce205dcd708dc9f0%40%3Cdev.apisix.apache.org%3E

**Comment by membphis** [comment]
There are compatibility issues with the current implementation.

We can also just modify the make install section. After installing via luarocks, the `lua` directory will be removed automatically.

I will submit a new PR later.

**Comment by membphis** [comment]
some

**Comment by moonming** [comment]
as discuss in mailling list, I will continue to fix this bug

**Comment by moonming** [comment]
> Some users like the folder "lua", which is easy to understand, so we can keep the current way.

which is not a good reason, we discuss in mailing list not in private channel from `some users`.

**Pull request closed without merging**
