### PR TITLE
add doc for plugin development

### PR DESCRIPTION
**Pull request by soulsoul**
#441  add doc ,just the outline,  enrich the content later.

### CODE REVIEW

**Comment by membphis** [comment]
how about add some example?

**Comment by membphis** [comment]
@soulsoul Please add a new link to this document in `doc / doc-index.md`.

**Comment by soulsoul** [comment]
i will enrich the document later and then  add the link in the right place

**Comment by moonming** [comment]
any update? @soulsoul

**Comment by membphis** [comment]
@soulsoul Please rebase your branch first.

**Comment by soulsoul** [comment]
> @soulsoul Please rebase your branch first.
This branch is 3 commits ahead of apache:master.

**Pull request closed without merging**
