### PR TITLE
license: add ASF header.

### PR DESCRIPTION
**Pull request by moonming**
NOTE: Please read the Contributing.md guidelines before submitting your patch:

https://github.com/iresty/apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one

### Summary

- add ASF header for all source code files.
- removed copyright info.
- add tool(https://github.com/apache/openwhisk-utilities) in travis CI to check ASF header.

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issues resolved

Fix #XXX

### CODE REVIEW

**Comment by membphis** [comment]
do we need to add a ignore file list?

**Comment by membphis** [comment]
image

**Comment by moonming** [comment]
> do we need to add a ignore file list?

sure, here is the exclude fiel list: https://github.com/iresty/apisix/pull/743/files#diff-fddd45f9d2486fc66aae183c85faeadcR81

**Comment by membphis** [comment]
@moonming https://travis-ci.org/iresty/apisix/builds/603466982#L696

please rebase your branch.

**Comment by membphis** [comment]
@moonming travis still fail

```
.travis/openwhisk-utilities/scancode/scanCode.py --config .travis/ASF-Release.cfg ./
Reading configuration file [.travis/ASF-Release.cfg]...
Scanning files starting at [./]...
Scan detected 1 error(s) in 1 file(s):
  [./dashboard/index.html]:
       1: file does not include required license header.
```

**Comment by juzhiyuan** [comment]
> index.html

So this file is using an incorrect ASF header?
https://github.com/iresty/apisix_dashboard_built/blob/fde8c24f536659e33e899d4adc3d6b48d658a6a2/index.html

**Comment by moonming** [comment]
> > index.html
> 
> So this file is using an incorrect ASF header?
> https://github.com/iresty/apisix_dashboard_built/blob/fde8c24f536659e33e899d4adc3d6b48d658a6a2/index.html

can you change to this style: https://github.com/apache/incubator-apisix/pull/743/files#diff-1fe3647ec3125ba1bcdbd7c830ada01d? thx

**Comment by membphis** [comment]
@moonming please rebase your branch.

**Pull request merged**
