### PR TITLE
doc(cn): add request-validation doc

### LINKED ISSUE #1882: doc: Chinese doc for plugin request-validator
here is the English doc: https://github.com/apache/incubator-apisix/commit/a6179996d4ddd8f99dfc44398666c282e6fd78ba#diff-14449a90466a7b8b69021054e24a789b

### PR DESCRIPTION
**Pull request by scaat**
### What this PR does / why we need it:

Add plugin of request-validation Chinese doc.

FIX #1882

### CODE REVIEW

**Comment by membphis** [comment]
this PR is duplicated with https://github.com/apache/incubator-apisix/pull/1932

**Comment by membphis** [comment]
@shuaijinchao do you have time to take a look at this PR?

**Comment by scaat** [comment]
I took a look, #1932 is still the old document translation, this pr is based on the latest master branch document translation. about #1933 @membphis

**Comment by shuaijinchao** [comment]
> I took a look, #1932 is still the old document translation, this pr is based on the latest master branch document translation. about #1933 @membphis

hello, I don't understand what you mean by the old document, what is the difference?

**Comment by scaat** [comment]
@shuaijinchao You can look #1926

**Comment by shuaijinchao** [comment]
@scaat  Generally, you need to request this job before dealing with this issue [#1882](https://github.com/apache/incubator-apisix/issues/1882). I think you should update on the [#1932](https://github.com/apache/incubator-apisix/pull/1932) basis after the [#1932](https://github.com/apache/incubator-apisix/pull/1932) merger instead of a new PR.

**Comment by membphis** [comment]
@scaat many sorry for this. I think we can close this PR. 
and please leave a message when you want to fix one issue next time.

**Pull request closed without merging**
