### PR TITLE
release: released 1.3 version.

### PR DESCRIPTION
**Pull request by moonming**

### CODE REVIEW

**Comment by moonming** [comment]
@totemofwolf any update?

**Comment by moonming** [comment]
@apache/apisix-committers please take a look

**Comment by sshniro** [comment]
I assume we can add the http logger as well for this release?

**Comment by moonming** [comment]
> I assume we can add the http logger as well for this release?

The release manager already sent the vote thread in mailing list, I think we can add this plugin in 1.4 version, which will release soon:)

**Pull request merged**
