### PR TITLE
bugfix(radixtree_host_uri): match priority, host > uri.

### LINKED ISSUE #761: bug: 三级泛解析路由规则无法匹配
### Environment

* apisix version (cmd: `apisix version`):master
* OS:docker

### Minimal test code / Steps to reproduce the issue
`
{"node":{"nodes":[
{"value":{"host":"lnp-admin.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000070","desc":"lap-admin-test"},"createdIndex":77,"key":"\/apisix\/routes\/00000000000000000077","modifiedIndex":77},
{"value":{"host":"apisix.test.com","plugins":{},"uri":"\/apisix\/*","service_id":"00000000000000000035","desc":"apisix.zhu"},"createdIndex":47,"key":"\/apisix\/routes\/00000000000000000038","modifiedIndex":47},
{"value":{"host":"lap.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000065","desc":"lap-test"},"createdIndex":74,"key":"\/apisix\/routes\/00000000000000000074","modifiedIndex":74},
{"value":{"host":"lnp.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"lnp-test"},"createdIndex":75,"key":"\/apisix\/routes\/00000000000000000075","modifiedIndex":75},
{"value":{"host":"lap-admin.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000071","desc":"lap-admin-test"},"createdIndex":76,"key":"\/apisix\/routes\/00000000000000000076","modifiedIndex":76},

## 下面2条是可以匹配到的
{"value":{"host":"yhs.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000065","desc":"yhs-demo-test-com"},"createdIndex":80,"key":"\/apisix\/routes\/00000000000000000080","modifiedIndex":80},
{"value":{"host":"pma.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"pma-demo-test-com"},"createdIndex":98,"key":"\/apisix\/routes\/00000000000000000097","modifiedIndex":98},
##

## 注意这里（匹配不上）:如果试用test2.demo.test.com去访问，匹配不到，直接用cdnserver那条路由了
{"value":{"host":"*.demo.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000066","desc":"*-demo-test-com"},"createdIndex":98,"key":"\/apisix\/routes\/00000000000000000098","modifiedIndex":99},

{"value":{"host":"apisix.test.com","plugins":{},"uri":"\/apisix\/*","service_id":"00000000000000000035","desc":"apisix-fu"},"createdIndex":48,"key":"\/apisix\/routes\/00000000000000000046","modifiedIndex":48},
{"value":{"host":"portainer.test.com","plugins":{},"uri":"\/*","service_id":"00000000000000000058","desc":"portainer-test"},"createdIndex":59,"key":"\/apisix\/routes\/00000000000000000059","modifiedIndex":59},

## 上面没又匹配到转到cdnserver##
{"value":{"plugins":{},"service_id":"00000000000000000092","desc":"cdnserver","uri":"\/*"},"createdIndex":93,"key":"\/apisix\/routes\/00000000000000000067","modifiedIndex":93}]
##
,"modifiedIndex":10,"createdIndex":10,"key":"\/apisix\/routes","dir":true},"action":"get"}

`

### PR DESCRIPTION
**Pull request by membphis**
Fix #761.

### CODE REVIEW

**Comment by lilien1010** [comment]
👍

**Comment by membphis** [comment]
Rebased right now

**Comment by lilien1010** [comment]
@membphis  when will this PR going to be merged into master？

**Comment by membphis** [comment]
Have you tested this feature at your ENV?

**Comment by membphis** [comment]
> @membphis when will this PR going to be merged into master?

Have you tested this feature at your ENV?

**Pull request merged**
