### PR TITLE
Adding CODE_STYLE.md and CODE_STYLE_CN.md for APISIX

### LINKED ISSUE #1846: bug: Missing the CODE_STYLE.md file
### Summary

I can't find the `CODE_STYLE.md` file in the project path：

```markdown
* [Code Style](../CODE_STYLE.md)
```

:((

### PR DESCRIPTION
**Pull request by yongboy**
### What this PR does / why we need it:

We missing the apisix's lua code style guide when writing a plugin, fixing the code bug.

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

### Summary

1. Adding `CODE_STYLE.md` base on `https://github.com/apache/incubator-apisix/blob/v1.2/CODE_STYLE.md`, and change it for meeting APISIX project
2. Adding `CODE_STYLE_CN.md` base on `https://juejin.im/post/5d71f9bcf265da03b76b437c`, and change it for readable :))
3. Fixing the `CODE_STYLE_CN.md` invalid path bug within `doc/zh-cn/README.md`

### Issues resolved

Fix #1846

### CODE REVIEW

**Comment by moonming** [comment]
@yongboy 
```
Scan detected 1 error(s) in 1 file(s):
  [./CODE_STYLE_CN.md]:
      20: line has trailing whitespace.
```
please fix the code style, which blocked CI.

**Comment by yongboy** [comment]
Removed line 20's trailing whitespace with the commit: 
https://github.com/apache/incubator-apisix/pull/1874/commits/a0ae4c1574aa1b7373c85e4794867f808c089eeb

But the CI still tell me the error:

```bash
  [./CODE_STYLE_CN.md]:
      20: line has trailing whitespace.
```

Checking the `CODE_STYLE_CN.md` line 20, you can't find the trailing whitespace now:

image

What should I do now ?

**Comment by membphis** [comment]
works fine at my local machine. I will rerun the Github Action.

```
Reading configuration file [.travis/ASF-Release.cfg]...
Scanning files starting at [./]...
All checks passed.
```

**Comment by membphis** [comment]
@yongboy many thx

**Pull request merged**
