### PR TITLE
[log] Optimize the buffer size and flush time

### PR DESCRIPTION
**Pull request by Miss-you**
1. buffer=4096 is better for Writes of more than PIPE_BUF bytes may be nonatomic
2. flush=1. Since the log buffer is lowered, the flush time should also be lowered.

NOTE: Please read the Contributing.md guidelines before submitting your patch:

https://github.com/apache/incubator-apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one

Fix https://github.com/apache/incubator-apisix/issues/1567

### CODE REVIEW

**Comment by membphis** [comment]
Have you done performance testing? Compare the two versions. @Miss-you

**Comment by membphis** [comment]
Have you done performance tests for two versions?

**Comment by Miss-you** [comment]
I will test this week

**Comment by membphis** [comment]
> I will do the performance test this week

I need your result to confirm if we can merge this PR. waiting for your response.

**Comment by membphis** [comment]
@Miss-you any news?

**Comment by membphis** [comment]
`buffer=16384 flush=1;`

I made a test, here is the result: 

`buffer=32768 flush=3;` -> qps 15459.15
`buffer=16384 flush=1;` -> qps 16057.62
`buffer=4096 flush=1;` -> qps 14940.23

**Comment by membphis** [comment]
@Miss-you please confirm this

**Comment by Miss-you** [comment]
hi, I also made a test.

```
4096  Requests/sec:  16079.75
8192 Requests/sec:  16389.52
16384 Requests/sec:  16395.30
32768 Requests/sec:  16459.71
```
I think a log buffer size of 8192 or 16384 would be appropriate.

On the other hand, the refresh time of 3 seconds is still relatively long, and 1 or 3 seconds doesn't particularly affect QPS.

So I also agree with `buffer=16384 flush=1; `

**Comment by membphis** [comment]
it seems blocked. @Miss-you need your help

image

**Comment by Miss-you** [comment]
> it seems blocked. @Miss-you need your help
> 
> image

I used git commit --amend to regenerate the new commitid, which should retrigger the travis

**Pull request merged**
