### PR TITLE
add cors plugin

### PR DESCRIPTION
**Pull request by renyineng**
NOTE: Please read the Contributing.md guidelines before submitting your patch:

https://github.com/apache/incubator-apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one

### Summary

SUMMARY_HERE

### Full changelog

add cors plugin

### CODE REVIEW

**Comment by moonming** [comment]
@Miss-you please have a look.

**Comment by Miss-you** [comment]
A brief look at the code:
1. Need process the "Preflight Request." which is an "OPTIONS" request.
2. Need test case.

**Comment by moonming** [comment]
@renyineng any update?

**Comment by moonming** [comment]
closed by https://github.com/apache/incubator-apisix/pull/1327

**Pull request closed without merging**
