### PR TITLE
update lua resty.

### LINKED ISSUE #1359: travis: update the openresty to `1.15.8.3` for Tengine ENV
Here is the source code:

https://github.com/apache/incubator-apisix/blob/master/.travis/linux_tengine_runner.sh#L57

### PR DESCRIPTION
**Pull request by Akayeshmantha**
### Issues resolved

Fix #1359

### CODE REVIEW

**Comment by membphis** [comment]
the Travis will reuse the cached item first, I cleaned the caches right now, and run the test case again.

**Comment by membphis** [comment]
it failed, please take a look:

https://travis-ci.org/github/apache/incubator-apisix/jobs/668486865?utm_medium=notification&utm_source=github_status

**Comment by moonming** [comment]
This file also contains many `openresty-1.15.8.2`, we better be unified into one.

**Comment by Akayeshmantha** [comment]
sure @membphis @moonming done

**Pull request merged**
